Article
tadeuasarro/PositioningAndFloatingElements pull request #1
Opened 2020-06-11 15:53 UTC by tadeuasarro

Veryfing Linters.

2020-06-15 16:06 UTC, tadeuasarro commented
#<Article>

The project has been finished.
Linters were used to verify the code.
README.md updated.

2020-06-15 23:46 UTC, HADDADSOHAIB requested changes
### Status: Change Required :recycle: 

### Hello @tadeuasarro  and @Alexoid1   :hand: 

### Good job, you did great job with the project :+1: 

### Unfortunately, there are still some changes to get the project approved:
- The pull request should look professional, please add a description to the pull request:
![Screenshot from 2020-06-16 00-21-14](https://user-images.githubusercontent.com/26064042/84715051-5a516f00-af67-11ea-8f6f-76f5938832dd.png)
This is not enough, also the title could be improved (ex: Newyork article clone, article clone ....).
- The logo should be a link, also the subscribe now and log in buttons are different from the original:
Original project:
![Screenshot from 2020-06-16 00-24-40](https://user-images.githubusercontent.com/26064042/84715299-efecfe80-af67-11ea-8d6f-1c3ce1b018e6.png)
Your project:
![Screenshot from 2020-06-16 00-26-04](https://user-images.githubusercontent.com/26064042/84715343-0e52fa00-af68-11ea-848c-3129330070e2.png)
- All social media icons should be links like the original:
![Screenshot from 2020-06-16 00-27-46](https://user-images.githubusercontent.com/26064042/84715422-4fe3a500-af68-11ea-9ab7-d4f92eb199b6.png)
- All the articles in the editor picks should be links:
![Screenshot from 2020-06-16 00-30-04](https://user-images.githubusercontent.com/26064042/84715518-95a06d80-af68-11ea-997f-f29c8b7e6987.png)
- A lot of contents are missing from this part, the project is a clone, so it must be close to the original website, please add the missing contents:
Your project:
![Screenshot from 2020-06-16 00-30-53](https://user-images.githubusercontent.com/26064042/84715588-cc768380-af68-11ea-8eb6-b35ba6af0c67.png)
Original:
![Screenshot from 2020-06-16 00-32-28](https://user-images.githubusercontent.com/26064042/84715622-e57f3480-af68-11ea-9cee-e8f0779e229c.png)
- All the elements in this section should be links:
![Screenshot from 2020-06-16 00-33-50](https://user-images.githubusercontent.com/26064042/84715718-3a22af80-af69-11ea-9299-47617852da8b.png)
also, try to improve the design, they're a lot of elements that need to be improved, for example:
![Screenshot from 2020-06-16 00-36-21](https://user-images.githubusercontent.com/26064042/84715792-75bd7980-af69-11ea-868a-00f3c45e164b.png)
Remove the duplicate top separater.
![Screenshot from 2020-06-16 00-37-20](https://user-images.githubusercontent.com/26064042/84715846-97b6fc00-af69-11ea-9db7-5e7be5354364.png)
Add separated between these two sections.
- There is a lot of space, please remove that:
original:
![Screenshot from 2020-06-16 00-38-12](https://user-images.githubusercontent.com/26064042/84715894-bcab6f00-af69-11ea-9798-7eb99cd4f366.png)
your project:
![Screenshot from 2020-06-16 00-38-05](https://user-images.githubusercontent.com/26064042/84715909-c59c4080-af69-11ea-8c20-769f5955aeba.png)
- All these elements should be links:
![Screenshot from 2020-06-16 00-39-36](https://user-images.githubusercontent.com/26064042/84715997-ea90b380-af69-11ea-8b4e-e23e49107211.png)
- Please remove inline styling (check the comments).
- [Optional] Think of using a main tag for the dominant part of your HTML file.
- [Optional] Think of using a footer tag instead of a div.
### Once you are done with the changes, asked for another code review

2020-06-15 23:46 UTC, HADDADSOHAIB commented on index.html
> +                        <span style='font-family:"Arial"'>Lorem ipsum dolor sit amet.</span>
Remove inline style, your styles should be on the css files

2020-06-16 21:07 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-16 21:28 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @tadeuasarro @Alexoid1** 
Good job with the improvements to the project :muscle:  
Your page meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition (in your CSS files).
- [ ] Don't use inline styles in your HTML
- [ ] content missing in a part of your page, check the original:

![](https://i.imgur.com/vweZoDUl.png)

and your clone:

![](https://i.imgur.com/hiPM2X3l.png)

### OPTIONAL

- [ ] it's recommended to use the main tag for the dominant content of the body of the document
- [ ] it's recommended to use nav tag for the major navigation links

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-06-16 21:28 UTC, andresporras3423 commented on index.html
> +                        <span style='font-family:"Arial"'>By LARRY BUCHANAN and JONATHAN CORUM</span>
Don't use inline styles

2020-06-16 21:28 UTC, andresporras3423 commented on styles.css
> +}
This selector has the same styles as the selector on line 102. Group selectors to minimize code.

2020-06-16 21:28 UTC, andresporras3423 commented on styles.css
> +}
This selector has the same styles as the selector on line 163. Group selectors to minimize code.

2020-06-16 21:28 UTC, andresporras3423 commented on styles.css
> +}
This selector has the same styles as selectors on lines 266 and 268. Group selectors to minimize code.

2020-06-16 21:28 UTC, andresporras3423 commented on styles.css
> +}
This selector has the same styles as the selector on line 591. Group selectors to minimize code.

2020-06-16 22:44 UTC, tadeuasarro commented
# The final version of the New York Article Clone:

Linters were run;
The text in image 2 has been fixed;
Selectors have been grouped in styles.css;
Inline styles were removed from index.html;
Some elements' colors have been fixed.

2020-06-16 23:55 UTC, elmejdki approved these changes
# Great job @team :clap: :blush:, your project looks super like the original :tophat: 
### status: approved

your project was approved you can merge now to master.

### Happy Coding
_If you have any type of questions or concerns you want to discuss them with me don't hesitate to contact me on slack_

2020-06-17 00:36 UTC, merged